@gateway = http://localhost:8000

//--------------------------------------------------------
// Acionamento Service (8060)
//--------------------------------------------------------
@acionamento-service = http://localhost:8000

# Ligar Alarme
POST {{acionamento-service}}/aciona/liga/0
Content-Type: application/json

{
    "cpf": "136"
}
###

# Desligar Alarme
POST {{acionamento-service}}/aciona/desliga/0
Content-Type: application/json

{
    "cpf": "136"
}
###

//--------------------------------------------------------
// Alarme Service (8090)
//--------------------------------------------------------
@alarme-service = http://localhost:8000
@id-alarme = 1

# Consultar Alarmes
GET {{alarme-service}}/alarme
Content-Type: application/json
###

# Consultar Alarme por ID
GET {{alarme-service}}/alarme/{{id-alarme}}
Content-Type: application/json
###

# Cadastrar Alarme
POST {{alarme-service}}/alarme
Content-Type: application/json

{
    "local": "CTC",
    "usuarios": ["136", "456"],
    "monitora": "Porta",
    "id": {{id-alarme}}
}
###

# Atualizar Alarme
PATCH {{alarme-service}}/alarme/{{id-alarme}}
Content-Type: application/json

{
    "local": "CTC Térreo",
    "usuarios": ["136", "438"],
    "monitora": "Porta"
}
###

# Excluir Alarme
DELETE {{alarme-service}}/alarme/{{id-alarme}}
Content-Type: application/json
###


//--------------------------------------------------------
// Disparo Service (8050)
//--------------------------------------------------------
@disparo-service = http://localhost:8000

# Disparar Alarme
POST {{disparo-service}}/dispara/10
Content-Type: application/json
###


//--------------------------------------------------------
// Logging Service (8070)
//--------------------------------------------------------
@logging-service = http://localhost:8070

# Consultar Logs
GET {{logging-service}}/logging
Content-Type: application/json
###

# Cadastrar Log
POST {{logging-service}}/logging
Content-Type: application/json

{
    "evento": "Teste",
    "status": "OK",
    "descricao": "Uma descrição"
}
###


//--------------------------------------------------------
// Notify Service (8040)
//--------------------------------------------------------
@notify-service = http://localhost:8040

# Cadastrar Notificação
POST {{notify-service}}/notify/
Content-Type: application/json

{
    "message": "Agua",
    "time": "10:34",
    "usuarios": "Lucas,João"
}
###


//--------------------------------------------------------
// Usuario Service (8080)
//--------------------------------------------------------
@usuario-service = http://localhost:8000
@cpf = 456

# Consultar Usuários
GET {{usuario-service}}/usuario/
Content-Type: application/json
###

# Consultar Usuário por CPF
GET {{usuario-service}}/usuario/{{cpf}}
Content-Type: application/json
###

# Cadastrar Usuário
POST {{usuario-service}}/usuario/
Content-Type: application/json

{
    "nome": "Lucas",
    "telefone": "489",
    "cpf": {{cpf}}
}
###

# Atualizar Usuário
PATCH {{usuario-service}}/usuario/{{cpf}}
Content-Type: application/json

{
    "nome": "Lucas",
    "telefone": "456"
}
###

# Excluir Usuário
DELETE {{usuario-service}}/usuario/{{cpf}}
Content-Type: application/json
###